### ISSUE TITLE
Navigating right in empty block causes crash

### ISSUE THREAD

**Issue by lightclient** [lithp/turtlescan#28]
If you try to navigate right in the txs pane of a block that is empty, the tui crashes.

**Comment by lithp** [comment]
embarrassingly enough, I had specifically considered this case but the bug re-emerged during a refactor. This is a sign that turtlescan has gotten big enough I can't fit it all into my head so I took the opportunity to start adding in a testing framework. This no longer crashes but I think tomorrow I'll fix it even further by disallowing you from selecting the "this block has no transactions" message.
